### ISSUE TITLE
JavaProperties.Load() ArgumentException about encoding iso-8859-2

### ISSUE THREAD

**Issue by voxoid0** [Kajabity/Kajabity-Tools#6]
Hi, I'm loading a Java properties file that was created from a java application, and am getting an encoding error.

Package version: 0.2.6862.30334

In .Net Standard library project.

ArgumentException message: `'iso-8859-2' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.`

Stack trace:
```
   at System.Text.EncodingTable.internalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at Kajabity.Tools.Java.JavaPropertyReader.Parse(Stream stream, Encoding encoding)

```

**Comment by voxoid0** [comment]
I was able to avoid the error by calling `JavaProperties.Load(stream, Encoding.UTF8)`, whereas previously I was only calling `JavaProperties.Load(stream)` . Honestly I'm not sure if UTF8 will be correct in all cases, but it's working for now.
